SELECT
  BPRNUM_0 AS BPCode,
  RTRIM (BPRNAM_0 + ' ' + BPRNAM_1) AS BPName
FROM
  EXPLOIT.BPARTNER AS BPARTNER
WHERE
  BPRNUM_0 = '#{BPCode}'
ORDER BY
  BPRNUM_0 ASC
OFFSET
  0 ROWS
FETCH NEXT
  1 ROWS ONLY
