SELECT
	IDENT1_0 AS PN,
	TYPDOC_0 AS DocType,
	NAM_0 AS Path,
CASE
	WHEN CAT_0 IN (3,4,5,6,8,12,13,14,19) THEN 'Drawing'
	WHEN CAT_0 IN (9,18) THEN 'Manual'
	WHEN CAT_0 IN (15) THEN 'Certificate'
	ELSE 'Other' END  AS  Cat
FROM EXPLOIT.AOBJTXT
WHERE ABREV_0='ITM' AND TYPDOC_0 !='GED' AND IDENT1_0 LIKE '#{PN}'
ORDER BY ROWID DESC
OFFSET
  #{offset} ROWS
FETCH NEXT
  #{limit} ROWS ONLY
